sm6160-common: fingerprint: Add blank callbacks for udfps
Without this, build will throw error below:

device/xiaomi/sdm845-common/fingerprint/BiometricsFingerprint.cpp:222:25: error: allocating an object of abstract class type 'android::hardware::bi>
        sInstance = new BiometricsFingerprint();

out/soong/.intermediates/hardware/interfaces/biometrics/fingerprint/2.3/android.hardware.biometrics.fingerprint@2.3_genc++_headers/gen/android/hard>
    virtual ::android::hardware::Return<void> onShowUdfpsOverlay() = 0;
                                              ^
out/soong/.intermediates/hardware/interfaces/biometrics/fingerprint/2.3/android.hardware.biometrics.fingerprint@2.3_genc++_headers/gen/android/hard>
    virtual ::android::hardware::Return<void> onHideUdfpsOverlay() = 0;
                                              ^
1 error generated.
22:26:27 ninja failed with: exit status 1

since we don't use it, for now let's just satisfy it with blank callbacks.

Former-commit-id: 3d920b522f8ad170a9433419813dd85a4176ec37

Co-authored-by: azrim <mirzaspc@gmail.com>
Co-authored-by: XtremeOrnob <xtreme.ornob@gmail.com>